### ISSUE TITLE
[Bug]: Could Not Detect Error When Plugin Is Working

### ISSUE THREAD

**Issue by DaChickenGamer** [Azn9/JetBrains-Discord-Integration#188]
### What happened?

So the Plugin is working fine on my Vesktop client but I'm still getting an error in the plugin page that it could not detect a running discord client.

![Screenshot from 2024-08-22 15-32-53](https://github.com/user-attachments/assets/0bc31273-79ca-4d49-8f00-7a5a5bddf571)

### IDE version

IntelliJ IDEA Ultimate 2024.1.4

### Plugin version

2.1.3

### What operating system are you using?

Linux

**Comment by Azn9** [comment]
May be a regression of #81

**Comment by TheAyes** [comment]
Seems like it's still happening on linux.

![image](https://github.com/user-attachments/assets/ed4fe2f9-3682-4fb7-a860-15e9c50c20ae)

OS: Nixos Unstable
Discord: Vesktop with arrpc

Miiiight be a nixos thing so I'd wait for someone else to confirm for another platform

**Comment by Azn9** [comment]
@TheAyes have you installed the IDE via either Snap, FlatPak or AppImage?

**Comment by Azn9** [comment]
@TheAyes the plugin uses the command `ps xo user:30,command` on linux to gather running programs. Can you send me the line corresponding to vesktop so I can add it to the detection? I only added it on Windows atm, as I don't use linux other than for servers 😅

**Comment by TheAyes** [comment]
So this is going to be tricky... Since by default programs on nixos are installed to the nix stores which contains a semi random hash to avoid conflicts between packages. Which means that every update this would be required to be updated manually (if hardcoded).

I'll have a look to see if I can find a better way of trying to detect it.

**Comment by TheAyes** [comment]
Alright. There's a couple of issues. firstly the "design choice" I mentioned above will make it a bit tedious. Secondly. Atleast for me there isn't a direct vesktop instance running. The Vesktop binary I execute instead starts several electron instances. This makes it really hard to get the actual command since there's not simply "one" correct answer.
Does it suffice if you can check if "any" is running?

If this is the case then modifying the command like this `ps xo user:30,command | grep "vesktop" | grep -Eoh '/.+$' | grep -v "grep" | head -1` always yields a result. While this works I have found a shorter variant to do this. however this modifies the original command and I'm unsure if it has any consequences.
`ps x -o command | grep "/vesktop" | grep -v "grep" | head -1`

this always returns "something" if vesktop is running. or nothing if it's not.

Long Command:
![image](https://github.com/user-attachments/assets/9c137523-0a17-4ffc-b64d-bd5d85367f7d)


Shorter Command:
![image](https://github.com/user-attachments/assets/bcdee043-1658-4d4b-a702-0133cf1e523e)

would this help?

P.S.: This might be alot easier on any other distro

**Comment by Azn9** [comment]
> ps x -o command | grep "/vesktop" | grep -v "grep" | head -1
this always returns "something" if vesktop is running. or nothing if it's not.
would this help?

That's exactly what I need, the current check is just something like "is there any line that contains `/discord`" 😅

> P.S.: This might be alot easier on any other distro

I don't know all have their specificities and the different packages managers don't really help 😔


However on windows I added a feature that just test the IPC file and don't care about the client if it can connect to one, I should port that to linux, it would prevent issues like that for other distros/clients 👀
