### ISSUE TITLE
[Bug]: WSL issues + "JBC_s"

### ISSUE THREAD

**Issue by jeffhubertorbeta-cp** [Azn9/JetBrains-Discord-Integration#229]
### Describe the feature you'd like

Currently unsupported version.

![image](https://github.com/user-attachments/assets/32ef5825-c7fe-45e5-b01e-d448a68ec5a0)

**Comment by Azn9** [comment]
Hello @jeffhubertorbeta-cp , according to Jetbrains, the plugin should be compatible with this version.
Are you facing any issue? If the plugin juste "don't work", can you please join the community server so that I can help you directly?

![Screenshot_2024-12-05-09-13-23-08_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/4cbb331b-c2fe-4bc3-b4fd-4ba82d156cf5)

**Comment by jeffhubertorbeta-cp** [comment]
Hello I just joined the dc server. it is not working on my config.

**Comment by Azn9** [comment]
Tried many things, two issues:
- Setting the application name to small changes JBC to JBC_s, so no data
- Even with the full name, it connects to discord but don't display anything

**Comment by Azn9** [comment]
\+ `Discord - No data found for application code phpstorm!`
